development:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :url) %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :url) %>
  channel_prefix: validators_app_production
